### ISSUE TITLE
Bug affiliated with package-name

### ISSUE THREAD

**Issue by jaunkst** [EvolveLabs/electron-updater#34] opened 2015-10-24 18:10 UTC
Not able to track this one down, there is no error logging on this one that I can find. App exits at launch without notice. changing the package-name fixes it. changing the package name back to a previously 'broken' package name will again keep the app from launching without any error.

**Comment by jaunkst** [comment] 2015-10-24 18:12
This would be broken
{
  "name": "app",
  "version": "1.0.0",
}

this would not be
{
  "name": "app-1",
  "version": "1.0.0",
}

changing it back would break again is there some kind of caching going on or something? Ive even tested to see if it was a problem with the npm repository but noting there.

**Comment by jaunkst** [comment] 2015-10-25 17:43
Okay I am closer to solving this one. I have old application updates in the pendingUpdatePath, removing the old files from application support path will fix this. I want to find a way to prevent this from happening if a bad update is published.

**Comment by jaunkst** [comment] 2015-10-25 17:54
This else if is closing the applciation when it belives there is an update in progress
but this isn't always the case. In my case I had published updates that where broken and
somehow ended up in this state indefinitely. I am not entirely sure what the best approach would be from here.

`} else if(ctx.updateInProgress) {
  // This can happen if the user tries to re-launch the app while an update is
  // currently in progress. In that case just close and wait.
  process.exit(0);
}`

**Comment by justinmchase** [comment] 2015-10-26 17:09
Hey, sorry about this. There is a known issue where if the updater crashes for some reason it can leave it in an "inprogress" state and keep looping that way. Its not ideal at all. We've had issues where electron itself can crash in certain cases, most recently there is a problem with allocating Buffers that the updater triggers due to downloading a lot of things at the same time. For reference see:

https://github.com/atom/electron/releases/tag/v0.33.2

So first off make sure you're using version `0.33.2` or greater. Also there is some cacheing that happens in the users appData dir, which should be near the log files. You can try clearing those out. If you are able to give me access to your app code so I can try to reproduce the issue that would help also.

But finally, there needs to be a more robust mechanism for when the update fails. Such that it doesn't get caught in a loop and has a way to basically to a full clean / re-install. I've been working on error reporting and error handling but in the case where the electron process just segfaults and stops suddenly there is not easy solution.

But if you can get me a code sample and I can reproduce it then I can probably try to help you get a simpler fix.

**Comment by justinmchase** [comment] 2015-10-26 17:13
@jaunkst You can email me directly if you want to share code or debug over a screen share session. Just let me know.

**Comment by jaunkst** [comment] 2015-10-27 12:31
@justinmchase thanks for the update. Currently I am just assuming it's all bad and clearing the update cache if the application is started and the file is flagged as inprogress. I think if we could check for another running instance and if the file is in progress then exit and if no instance is running and the file is in progress then assume the data is bad and full install?

**Comment by justinmchase** [comment] 2015-10-27 15:12
Yes exactly. We need a global mutex to do this properly however. Fortunately this feature was just added to electron 5 days ago :)

https://github.com/atom/electron/pull/3145

I may be able to use this to give a much more robust instance management system. The only limitation is that it seems like it will force the app to become single instanced... which frankly isn't that bad.

**Comment by jaunkst** [comment] 2015-10-27 17:19
:+1: 
I would be okay with that, why don't we update and emit the INPROGRESS so we can let the developer decide the action to take for multi-instance / single-instance until we can resolve the issue for both scenarios?

command.js
`
			fs.unlink(pendingUpdatePath, function (err, valid) {
				that.emit('updateInProgress');
			})
`

main.js
`
    updater.on('updateInProgress', function () {
       // some more robust action to take depending on my use-case.
       app.quit();
    })
`

**Comment by jaunkst** [comment] 2015-10-27 17:22
may want to rename the event though for brevity :)

**Comment by justinmchase** [comment] 2015-10-30 14:05
If the developer uses the single process api we were talking about earlier, then the only time the `'updateInProgress'` event would fire would be in the case where there was a problem and the updater exited unexpectedly.

I also need to cover the case where the update fails, and just launches the app as is, instead of getting caught in a loop of constantly trying to update.

**Comment by jaunkst** [comment] 2015-11-04 15:17
any thoughts on handling when the update fails ?

**Comment by justinmchase** [comment] 2015-11-04 19:43
There's a pull request for you to take a look at.
https://github.com/EvolveLabs/electron-updater/pull/36

**Comment by justinmchase** [comment] 2015-12-15 18:02
Fixed by #36

**Closed by justinmchase** 2015-12-15 18:02 UTC
Labels: bug
